#!/bin/zsh

docker run -d \
-e "KONG_ROLE=data_plane" \
-e "KONG_DATABASE=off" \
-e "KONG_VITALS=off" \
-e "KONG_CLUSTER_MTLS=pki" \
-e "KONG_CLUSTER_CONTROL_PLANE=5353266df3.us.cp.konghq.com:443" \
-e "KONG_CLUSTER_SERVER_NAME=5353266df3.us.cp.konghq.com" \
-e "KONG_CLUSTER_TELEMETRY_ENDPOINT=5353266df3.us.tp.konghq.com:443" \
-e "KONG_CLUSTER_TELEMETRY_SERVER_NAME=5353266df3.us.tp.konghq.com" \
-e "KONG_CLUSTER_CERT=-----BEGIN CERTIFICATE-----
MIICHjCCAcSgAwIBAgIBATAKBggqhkjOPQQDBDBAMT4wCQYDVQQGEwJVUzAxBgNV
BAMeKgBrAG8AbgBuAGUAYwB0AC0AawB1AG0AYQBnAGEAaQAtAGwAbwBjAGEAbDAe
Fw0yNjA5MTQwNDU5MzZaFw0zNjA5MTQwNDU5MzZaMEAxPjAJBgNVBAYTAlVTMDEG
A1UEAx4qAGsAbwBuAG4AZQBjAHQALQBrAHUAbQBhAGcAYQBpAC0AbABvAGMAYQBs
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzMoz6Un5RTjKRR5koXjYfQvJEW8g
pS/c4AoA7QIPMV+Ofo/TftlKLOKkigWu6a0veJZuQv/6RVZnAtxbYihr+aOBrjCB
qzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIABjAdBgNVHSUEFjAUBggrBgEFBQcD
AQYIKwYBBQUHAwIwFwYJKwYBBAGCNxQCBAoMCGNlcnRUeXBlMCMGCSsGAQQBgjcV
AgQWBBQBAQEBAQEBAQEBAQEBAQEBAQEBATAcBgkrBgEEAYI3FQcEDzANBgUpAQEB
AQIBCgIBFDATBgkrBgEEAYI3FQEEBgIEABQACjAKBggqhkjOPQQDBANIADBFAiAt
N1Ut2bv+T108fa1d/AdJ2CsoU/lA+wKZQcERvV3AJQIhAO5WJZU+Kxpu0lXNg4xq
OeXSKotqrOn2vd78ki7Nspjm
-----END CERTIFICATE-----" \
-e "KONG_CLUSTER_CERT_KEY=-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcuipMr8fcxQicSwP
2EFLRqgsuYO4K0HYiYKRfgvsE4GgCgYIKoZIzj0DAQehRANCAATMyjPpSflFOMpF
HmSheNh9C8kRbyClL9zgCgDtAg8xX45+j9N+2Uos4qSKBa7prS94lm5C//pFVmcC
3FtiKGv5
-----END PRIVATE KEY-----" \
-e "KONG_LUA_SSL_TRUSTED_CERTIFICATE=system" \
-e "KONG_KONNECT_MODE=on" \
-e "KONG_ROUTER_FLAVOR=expressions" \
-e "KONG_UNTRUSTED_LUA=lax" \
-p 8000:8000 \
-p 8443:8443 \
kong/kong-gateway:3.15
